// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fjorubordid_database.Data;

#nullable disable

namespace fjorubordiddatabase.Migrations
{
    [DbContext(typeof(FjorubordidDbContext))]
    [Migration("20221216164239_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fjorubordid_database.Models.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrinkId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("DrinkId");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            DrinkId = 1,
                            Description = "Egils Gull 0.5l",
                            Name = "Egils Gull 0.5l",
                            Quantity = 1,
                            UnitPrice = 1400
                        },
                        new
                        {
                            DrinkId = 2,
                            Description = "Egils Gull 0.3l",
                            Name = "Egils Gull 0.3l",
                            Quantity = 1,
                            UnitPrice = 1200
                        },
                        new
                        {
                            DrinkId = 3,
                            Description = "Flaska af hvítvíni hússins",
                            Name = "Hvítvín hússins",
                            Quantity = 1,
                            UnitPrice = 7200
                        },
                        new
                        {
                            DrinkId = 4,
                            Description = "Flaska af rauðvíni hússins",
                            Name = "Rauðvín hússins",
                            Quantity = 1,
                            UnitPrice = 7200
                        },
                        new
                        {
                            DrinkId = 5,
                            Description = "Pepsi í gleri 330ml",
                            Name = "Pepsi",
                            Quantity = 1,
                            UnitPrice = 500
                        },
                        new
                        {
                            DrinkId = 6,
                            Description = "Pepsi í gleri 330ml",
                            Name = "Pepsi Max",
                            Quantity = 1,
                            UnitPrice = 500
                        },
                        new
                        {
                            DrinkId = 7,
                            Description = "7up í gleri 330ml",
                            Name = "7up",
                            Quantity = 1,
                            UnitPrice = 500
                        },
                        new
                        {
                            DrinkId = 8,
                            Description = "Appelsín í gleri 330ml",
                            Name = "Appelsín",
                            Quantity = 1,
                            UnitPrice = 500
                        },
                        new
                        {
                            DrinkId = 9,
                            Description = "Kristall í gleri 330ml án bragðefna",
                            Name = "Kristall",
                            Quantity = 1,
                            UnitPrice = 500
                        },
                        new
                        {
                            DrinkId = 10,
                            Description = "Sleipnir Pale Ale frá Ölvisholt Brugghús 330ml",
                            Name = "Sleipnir Pale Ale",
                            Quantity = 1,
                            UnitPrice = 1600
                        });
                });

            modelBuilder.Entity("fjorubordid_database.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Description = "3ja rétta 400g",
                            Name = "3ja rétta 400g",
                            Quantity = 1,
                            UnitPrice = 14175
                        },
                        new
                        {
                            FoodId = 2,
                            Description = "3ja rétta 300g",
                            Name = "3ja rétta 300g",
                            Quantity = 1,
                            UnitPrice = 12250
                        },
                        new
                        {
                            FoodId = 3,
                            Description = "Leturhumar 400g",
                            Name = "Humar 400g",
                            Quantity = 1,
                            UnitPrice = 10750
                        },
                        new
                        {
                            FoodId = 4,
                            Description = "Leturhumar 300g",
                            Name = "Humar 300g",
                            Quantity = 1,
                            UnitPrice = 8650
                        },
                        new
                        {
                            FoodId = 5,
                            Description = "Leturhumar 250g",
                            Name = "Humar 250g",
                            Quantity = 1,
                            UnitPrice = 8050
                        },
                        new
                        {
                            FoodId = 6,
                            Description = "Aðalréttur",
                            Name = "Humarsúpa",
                            Quantity = 1,
                            UnitPrice = 4190
                        },
                        new
                        {
                            FoodId = 7,
                            Description = "Forréttur",
                            Name = "Humarsúpa",
                            Quantity = 1,
                            UnitPrice = 3250
                        },
                        new
                        {
                            FoodId = 8,
                            Description = "Grænmetisréttur",
                            Name = "Grænmetisréttur",
                            Quantity = 1,
                            UnitPrice = 4190
                        },
                        new
                        {
                            FoodId = 9,
                            Description = "Lambahryggvöðvi",
                            Name = "Lambahryggvöðvi",
                            Quantity = 1,
                            UnitPrice = 6250
                        },
                        new
                        {
                            FoodId = 10,
                            Description = "Barnamatseðill",
                            Name = "Kjúklinganaggar",
                            Quantity = 1,
                            UnitPrice = 990
                        },
                        new
                        {
                            FoodId = 11,
                            Description = "Barnamatseðill",
                            Name = "Samloka",
                            Quantity = 1,
                            UnitPrice = 990
                        },
                        new
                        {
                            FoodId = 12,
                            Description = "Eftirréttur tertusneið",
                            Name = "Eftirréttur",
                            Quantity = 1,
                            UnitPrice = 1650
                        });
                });

            modelBuilder.Entity("fjorubordid_database.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.ToTable("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
